# Generated by Django 4.1.13 on 2026-03-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_mico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='oper_desc',
            field=models.TextField(default='', verbose_name='공정 설명'),
        ),
        migrations.AddField(
            model_name='category',
            name='oper_id',
            field=models.CharField(default='', max_length=100, verbose_name='공정 ID'),
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.CharField(default='', max_length=100, verbose_name='제품명'),
        ),
    ]
