# Generated by Django 4.1.13 on 2026-03-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_mico', '0002_category_oper_desc_category_oper_id_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='device',
            field=models.CharField(default='', max_length=100, verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='fab',
            field=models.CharField(default='', max_length=100, verbose_name='FAB'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='maker',
            field=models.CharField(default='', max_length=100, verbose_name='Maker'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='recipe_id',
            field=models.CharField(default='', max_length=100, verbose_name='Recipe ID'),
        ),
    ]
