# Generated by Django 4.1.13 on 2026-03-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_mico', '0003_subcategory_device_subcategory_fab_subcategory_maker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='apc_para',
            field=models.CharField(default='', max_length=100, verbose_name='APC Para'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='if_rr',
            field=models.IntegerField(blank=True, null=True, verbose_name='IF RR'),
        ),
        migrations.AddField(
            model_name='detail',
            name='pre_target',
            field=models.IntegerField(default=0, verbose_name='Pre Target'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='pre_thk_period',
            field=models.IntegerField(default=0, verbose_name='Pre THK Period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='rr_para',
            field=models.CharField(blank=True, choices=[('pad', 'Pad'), ('disk', 'Disk'), ('head', 'Head')], default='', max_length=10, verbose_name='RR Para'),
        ),
        migrations.AddField(
            model_name='detail',
            name='rr_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='RR Period'),
        ),
        migrations.AddField(
            model_name='detail',
            name='target',
            field=models.IntegerField(default=0, verbose_name='Target'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='thk_para',
            field=models.CharField(default='', max_length=100, verbose_name='THK Para'),
            preserve_default=False,
        ),
    ]
