# Generated by Django 4.1.13 on 2026-03-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_mico', '0004_detail_apc_para_detail_if_rr_detail_pre_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='offset_group',
            field=models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N')], default='', max_length=1, verbose_name='Offset Group'),
        ),
        migrations.AddField(
            model_name='detail',
            name='rr_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='RR Max'),
        ),
    ]
