# Generated by Django 4.1.13 on 2026-03-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_mico', '0005_detail_offset_group_detail_rr_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name',
        ),
    ]
