# Generated by Django 4.1.13 on 2026-03-17 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup_mico', '0006_remove_category_name_remove_detail_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('reply', models.TextField(blank=True, default='', verbose_name='답변')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocs', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voc_replies', to=settings.AUTH_USER_MODEL, verbose_name='답변자')),
            ],
            options={
                'verbose_name': 'VOC',
                'verbose_name_plural': 'VOCs',
                'ordering': ['-created_at'],
            },
        ),
    ]
