# Generated by Django 4.1.13 on 2026-03-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_mico', '0007_voc'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='그룹명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_groups', to='setup_mico.category', verbose_name='카테고리')),
                ('subcategories', models.ManyToManyField(blank=True, related_name='recipe_groups', to='setup_mico.subcategory', verbose_name='레시피')),
            ],
            options={
                'verbose_name': 'Recipe Group',
                'verbose_name_plural': 'Recipe Groups',
                'ordering': ['category__product', 'category__oper_id', 'name'],
            },
        ),
    ]
