# Generated by Django 4.1.13 on 2026-03-18 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup_mico', '0009_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '생성'), ('update', '수정'), ('delete', '삭제')], max_length=10, verbose_name='작업')),
                ('model_type', models.CharField(choices=[('Category', 'Category'), ('SubCategory', 'SubCategory'), ('Detail', 'Detail'), ('RecipeGroup', 'Recipe Group')], max_length=20, verbose_name='구분')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='대상 ID')),
                ('object_repr', models.CharField(max_length=500, verbose_name='대상')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='작업 일시')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='변경 내용')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_histories', to=settings.AUTH_USER_MODEL, verbose_name='작업자')),
            ],
            options={
                'verbose_name': 'Setup History',
                'verbose_name_plural': 'Setup Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
