# Generated by Django 4.1.13 on 2026-03-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_mico', '0010_setuphistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='oper_desc',
            field=models.CharField(default='', max_length=100, verbose_name='공정 설명'),
        ),
    ]
