# Generated by Django 4.1.13 on 2026-03-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_mico', '0011_category_oper_desc_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='family',
            field=models.CharField(default='', max_length=100, verbose_name='Family'),
        ),
    ]
