# Generated by Django 4.1.13 on 2026-03-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_mico', '0012_add_family_to_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='family',
            field=models.CharField(choices=[('NAND', 'NAND'), ('DRAM', 'DRAM')], default='', max_length=10, verbose_name='Family'),
        ),
    ]
