# Generated by Django 4.1.13 on 2026-03-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_mico', '0013_family_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='pad_seperation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pad Seperation'),
        ),
        migrations.AddField(
            model_name='detail',
            name='pre_oper_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pre Oper Code'),
        ),
        migrations.AddField(
            model_name='detail',
            name='pre_oper_code2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pre Oper Code2'),
        ),
        migrations.AddField(
            model_name='detail',
            name='pre_oper_code3',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pre Oper Code3'),
        ),
        migrations.AddField(
            model_name='detail',
            name='pre_oper_code4',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pre Oper Code4'),
        ),
        migrations.AddField(
            model_name='detail',
            name='pre_oper_desc',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pre Oper Desc'),
        ),
        migrations.AddField(
            model_name='detail',
            name='pre_oper_desc2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pre Oper Desc2'),
        ),
        migrations.AddField(
            model_name='detail',
            name='pre_oper_desc3',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pre Oper Desc3'),
        ),
        migrations.AddField(
            model_name='detail',
            name='pre_oper_desc4',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pre Oper Desc4'),
        ),
        migrations.AddField(
            model_name='detail',
            name='pre_oper_para',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pre Oper Para'),
        ),
        migrations.AddField(
            model_name='detail',
            name='pre_oper_para2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pre Oper Para2'),
        ),
        migrations.AddField(
            model_name='detail',
            name='pre_oper_para3',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pre Oper Para3'),
        ),
        migrations.AddField(
            model_name='detail',
            name='pre_oper_para4',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pre Oper Para4'),
        ),
        migrations.AddField(
            model_name='detail',
            name='pre_thk_para_itm',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pre THK Para ITM'),
        ),
        migrations.AddField(
            model_name='detail',
            name='rr_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='RR Count'),
        ),
        migrations.AddField(
            model_name='detail',
            name='rr_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='RR Weight'),
        ),
    ]
