# Generated by Django 4.1.13 on 2026-03-31 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_mico', '0016_add_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, verbose_name='Spotfire URL')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_link', to='setup_mico.category', verbose_name='공정 (Category)')),
            ],
            options={
                'verbose_name': 'Simulation Link',
                'verbose_name_plural': 'Simulation Links',
                'ordering': ['category__product', 'category__oper_desc'],
            },
        ),
    ]
