# Generated by Django 5.2.12 on 2026-04-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setup_mico", "0017_add_simulation_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="channel_id",
            field=models.CharField(
                default="500019173", max_length=100, verbose_name="Channel ID"
            ),
        ),
        migrations.AddField(
            model_name="detail",
            name="fb_type",
            field=models.CharField(
                choices=[("TIME", "TIME"), ("PRESSURE", "PRESSURE")],
                default="TIME",
                max_length=10,
                verbose_name="FB Type",
            ),
        ),
        migrations.AddField(
            model_name="detail",
            name="rr_alarm_sigma",
            field=models.IntegerField(default=10, verbose_name="RR Alarm Sigma"),
        ),
    ]
