# Generated by Django 4.1.13 on 2026-05-12 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup_mico', '0019_fix_rr_para_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pol_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pol Type'),
        ),
        migrations.CreateModel(
            name='PolTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pol_type', models.IntegerField(unique=True, verbose_name='Pol Type 번호')),
                ('steps', models.JSONField(default=list, verbose_name='Step 목록')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pol_type_configs', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': 'Pol Type Config',
                'verbose_name_plural': 'Pol Type Configs',
                'ordering': ['pol_type'],
            },
        ),
    ]
