# Generated by Django 4.1.13 on 2026-07-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setup_mico", "0020_add_poltypeconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="rr_para",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pad", "Pad"),
                    ("disk", "Disk"),
                    ("head", "Head"),
                    ("dresser_cutting_rate", "Dresser Cutting Rate"),
                ],
                default="",
                max_length=30,
                verbose_name="RR Para",
            ),
        ),
    ]
