# Generated by Django 4.1.13 on 2026-08-19 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup_mico', '0021_alter_detail_rr_para'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulFormulaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, default='', max_length=20, verbose_name='Zone')),
                ('params', models.JSONField(default=dict, verbose_name='산식 파라미터')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simul_formulas', to='setup_mico.category', verbose_name='공정 (Category)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simul_formulas', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': 'Simulation 산식 설정',
                'verbose_name_plural': 'Simulation 산식 설정',
                'ordering': ['category__product', 'category__oper_desc', 'zone'],
                'unique_together': {('category', 'zone')},
            },
        ),
    ]
