# Generated by Django 4.1.13 on 2026-08-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setup_mico", "0021_alter_detail_rr_para"),
    ]

    operations = [
        migrations.AddField(
            model_name="detail",
            name="pre_thk_vm_source",
            field=models.CharField(
                choices=[("AUTO", "AUTO"), ("POST", "POST")],
                default="AUTO",
                max_length=4,
                verbose_name="Pre THK VM Source",
            ),
        ),
    ]
